language: java

jdk:
  - oraclejdk8

env:
  matrix:
    - PROFILE=ci
    - PROFILE=springldap-next

addons:
  apt:
    packages:
    - oracle-java8-installer

cache:
  directories:
    - $HOME/.m2

before_install:
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml

install: true

script: "mvn clean dependency:list test -P${PROFILE} -Dsort"
